services:
  - type: web
    name: salon-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MYSQL_PUBLIC_URL
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SMS_PROVIDER
        value: fast2sms
      - key: FAST2SMS_API_KEY
        sync: false
      - key: FAST2SMS_ROUTE
        value: q
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
